### ISSUE TITLE
Is there a way to monitor ALL servers for the ./status/ without logging in?

### ISSUE THREAD

**Issue by infracritical** [louislam/uptime-kuma-wiki#14]
Is there a way to monitor ALL servers for the ./status/ without logging in?

**Comment by Justman10000** [comment]
> Is there a way to monitor ALL servers for the ./status/ without logging in?

Wrong repo! This is for the documentation, not Kuma himself! See [uptime-kuma](/louislam/uptime-kuma)

**Comment by Justman10000** [comment]
@louislam

**Comment by Justman10000** [comment]
@infracritical
