### ISSUE TITLE
Potential Small Typo in How-to-Update.md

### ISSUE THREAD

**Issue by craigpryde** [louislam/uptime-kuma-wiki#60]
Hey @louislam,

Love the tool, Just wanted to check on the `How-to-Update.md`, The commands for docker compose are  listed as `docker compose` over `docker-compose` (Without the '-'). Im still fairly new to docker so i might be wrong but i think it need's to include the `-` to work with the standard docker-compose install.

Wanted to check as this might be easiest for yourself to fix over myself submitting a PR onto the pile. 

Cheers
Craig

**Comment by louislam** [comment]
When I learnt docker compose, the command is `docker-compose`. And it is a standalone tool, people have to install separately.

Maybe they now integrated this into the docker? If yes, we can change it to `docker compose`.

**Comment by craigpryde** [comment]
Hey @louislam, I think my initial message was unclear. It's currently `docker compose` in your `How-to-Update.md` It should be `docker-compose` as we both mentioned due to it being a stand alone tool. 

Sorry for any confusion.

**Comment by louislam** [comment]
Oh, I got it now, these commands are written by another contributor. I didn't know noticed that is already in `docker compose` until now.

I just checked

`docker-compose` = V1
`docker compose` = V2

V1 is actually deprecated, V2 is recommended by Docker official.

Install V2 plugin:
https://docs.docker.com/compose/install/linux/
